mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pollapp/',include('pollapp.urls', namespace='pollapp')),
]

pollapp/urls.py
from django.urls import path
from django.contrib import admin
from . import views
from pollapp.views import  GuestListView , CSVExportView
from django.conf import settings
from django.conf.urls.static import static
#, GuestFormView , GuestConfirmView , GuestRegisterView , GuestReplyView 

app_name = 'pollapp'
urlpatterns = [
	path('admin/', admin.site.urls),
#主催者の確認ページ
#	path('1/guestlist/', GuestListView.as_view(), name='list'),
	path('2/guestlist/', GuestListView, name='guestlist'),


#ゲストユーザ登録の為の入力フォーム
	path('2/guestform/', views.GuestFormView, name='guestform'),	

#ゲストユーザの情報をCSVで出力するページ
	path('2/csvexport/', CSVExportView, name='csvexport'),

#テストページ
	path('2/testpage/', views.testpage, name='testpage'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pollapp/models.py
from django.conf import settings
from django.db import models

class Guest(models.Model):
	name = models.CharField(
		max_length=30,
		#verbose_name='名前',
		help_text='名前を入力して下さい',
		)				#デフォルトwidget(TextInput)、通常A stringを使用(Max_Min_lengthがある場合、Max_length/Min_lengthを使用)

	furi = models.CharField(
		max_length=30,
		#verbose_name='フリガナ',
		help_text='名前のフリガナを入力してください',
		)

	email = models.EmailField(
		unique=True,
		default='',
		null=False,
		max_length=255,
		#verbose_name='メールアドレス',
		help_text='メールアドレスを入力してください',
		)				#デフォルトのwidget(EmailFields)/EmailValidatorを使用

	memo = models.TextField(
		blank=True,
		#verbose_name='メモ',
		help_text='参加人数が複数の場合や遅れて参加の場合は記入してください',
		) 				#blank:空欄を許容する


	def __str__(self): 										#モデル内部の情報を文字列で表現(特殊メソッド)
		return u"{0}:{1}...".format(self.id, self.name, self.furi, self.email, self.memo)
															#返り値はu(中身：format({0}=id,{1}=name,....と続いていく)

class Maildata(models.Model):
	datetime = models.DateTimeField('連絡日・時間')
	mail_to = models.EmailField(Guest) #verbose_name='To')

	def __str__(self):
		message = '{0} {1}'
		return message.format(self.mail_to)



# Create your models here.
#

pollapp/forms.py
from django import forms
from .models import Guest
from django.core.exceptions import ValidationError

class GuestsForm(forms.ModelForm):
	class Meta:
		model = Guest
		fields = ('name','furi','email','memo')
		labels = {
			'name':'名前' ,
			'furi':'フリガナ' ,
			'email':'メールアドレス' ,
			'memo':'メモ',
					}
		widgets ={
			'name':forms.TextInput(attrs={'size':42}),
			'furi':forms.TextInput(attrs={'size':42}),
			'email':forms.EmailInput(attrs={'size':42}),
			'memo':forms.Textarea(attrs={'cols':40, 'rows':2}),
		}
		requireds = {
			'name': True ,
			'furi': True ,
			'email': True ,
			'memo': None,
					}
		# requiredsはTrueかNone/’’を必ず入れる

pollapp/views.py
import time
import sched
import csv
import io
from datetime import datetime
from django.views.generic.base import TemplateView
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse_lazy
from .forms import GuestsForm
from .models import Guest
from django.views.decorators.http import require_POST
from django.core.mail import BadHeaderError, send_mail, EmailMessage



def GuestListView(request):
	form = GuestsForm(request.POST or None)
	if request.method == 'POST':
		form.cleaned_data

	d = {
		'Guests': Guest.objects.all(),
	}
	return render(request,'2/guestlist.html',d)


def GuestFormView(request):
	form = GuestsForm(request.POST or None)

	context = {
		'form': form,
	}
	return render(request,'2/guestform.html', context )


def testpage(request):
	form = GuestsForm(request.POST or None)
	if request.method == 'POST':
		if form.is_valid():
			Guest.objects.create(**form.cleaned_data)

	temp_email = request.POST['email']
	temp_name = request.POST['name']
	temp_furi = request.POST['furi']
	temp_memo = request.POST['memo']

	if 'email' in request.POST:
		subject = "登録確認のお知らせ"
		message = "以下のように登録しました。\n 名前：%s \n フリガナ：%s \n メールアドレス：%s \n 備考：%s \n当日を待ちしております。" %(temp_name ,temp_furi ,temp_email ,temp_memo)
		from_email = "event.message.for.guests@gmail.com"
		to = ["event.message.for.guests@gmail.com"]
		bcc = [temp_email]
	email=EmailMessage(subject, message, from_email, to, bcc)
	email.send()

	context = {
			'form': form,
			}
	return render(request, '2/testpage.html', context)

"""
def mailsend():

	subject = "Subject here"
	message = "message_test"
	from_email = "event.message.for.guests@gmail.com"
	to = ["event.message.for.guests@gmail.com"]
#	bcc = [temp_email]

	email=EmailMessage(subject, message, from_email, to, bcc)
	email.send()
"""

def CSVExportView(request):
	response = HttpResponse(content_type='text/csv')
	response['Content-Disposition'] = 'attachment; filename="guest.csv"'
	writer = csv.writer(response)
	for guest in Guest.objects.all():
		writer.writerow([guest.name, guest.furi, guest.memo])
	return response

# Create your views here.

pollapp/templates/2/guest_confirm.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>イベント紹介＆ゲスト入力</title>
		<link rel="stylesheet" type="text/css" href="{% static 'css/commom.css' %}">
	</head>
<body>
	<p>prototype</p>

	{% for field in form %}
	<div class="form-group">
		<label for="{{ field.id_for_label }}">{{ filed.label_tag }}</label>
		{{ field.value }}
	</div>
	{% endfor %}

	<form action="{% url 'eventform:guest_form' %}" method="POST">
		<button type="submit" > 戻る </button>
		{% for field in form %}{{ field.as_hidden}}{% endfor %}
		{% csrf_token %}
	</form>
	<hr>
	<form action="{% url 'eventform:guest_reply' %}" method="POST">
		<button type="submit">送信</button>
		{% for field in form %}{{field.as_hidden }}{% endfor %}
		{% csrf_token %}
	</form>
</body>
</html>

pollapp/templates/2/guest_reply.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>登録が完了しました</title>
		<link rel="stylesheet" type="text/css" href="{% static 'css/commom.css' %}">
	</head>

	<body>
		<p>登録が完了しました。</p>
		<p>画面を閉じてください。</p>


	</body>
</html>

pollapp/templates/2/guestform.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>入力フォーム</title>
		<meta name= "viewport"
		 content="width=device-width,user-scalable=no,maximum-scale=1">
		<link rel="stylesheet" type="text/css" href="{% static 'css/guestform.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/guestform_res.css' %}">
	</head>
	<body>
		<div class="header">

		</div>

		<div class="main">	
			<p>以下の登録項目にご記入ください。</p>
			<form action ="{% url 'pollapp:testpage'%}" method="post">
			<ul>
				<li>名前</li>
				<li class="form">{{ form.name }}</li>
				<li>フリガナ</li>
				<li class="form">{{ form.furi }}</li>
				<li>メールアドレス</li>
				<li class="form">{{ form.email }}</li>
				<li>メモ</li>
				<li class="form">{{ form.memo }}<li/>
			</ul>
			<p>※他の参加者をお連れする方は、メモにその方の名前をご記入ください。</p>
			
			{% csrf_token %}
			<button type="submit" class="btn">送信</button>
			</form>
		</div>

		<div class="footer">
			
		</div>
	</body>
</html>

pollapp/templates/2/guestformのコピー.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>イベント紹介＆ゲスト入力</title>
		<link rel="stylesheet" type="text/css" href="{% static 'css/commom.css' %}">
	</head>
<body>
	<p>prototype</p>

<!--画像　ここからアップロード＋表示へ-->
	{% load static%}
<!--<	
img src="{% static "eventform/background.jpeg"%}" style="max-height:500px" alt="テスト" title="background"
>--->

<!-- 文章 -->
<!--関数を設置 
	！！！これをmodels & formに作成！！！-->
	<p>説明文章</p>
	<ul>
		<li>場所：</li>
		<li>時間：</li>
		<li>会費：</li>
		<li>人数：</li>
	</ul>
<br>
<hr>
<br>
	<form action ="" method="post">
		{{ form.errors.guest }}
	<ul>
<!---		<li>
			<label>名前：</label>
			<label>{{ form.name }}</label>
			<br>
		</li>
		<li>
			<div class="furigana">
			<label>フリガナ：</label>
			<label>{{ form.furi }}</label>
			<br>
		</li>
--->
		<li>
			<div class="mailaddress">
			<label>メールアドレス：</label>
			<label>{{ form.email }}</label>
			<br>
		</li>
<!--
		<li>
			<div class="remarks">
			<label>備考：</label>
			<label>{{ form.remarks }}</label>
			<br>
		</li>
--->
		<li>
			<br><br><br>
			{% csrf_token %}
			<input type="submit" value="送信">
		</li>
	</ul>
	</form>
</body>
</html>

pollapp/templates/2/guestlist.html
<!DOCTYPE html>
<html>
<head>
  <title>参加者一覧</title>
</head>
  <body>

    <p>主催者用メージ</p>
      <p><a href="{% url 'pollapp:guestform' %}">フォームへ</a></p>
      <br>
      <p><a href="{% url 'pollapp:csvexport' %}">CSV出力</a></p>
      <form method="post" action="">

      <table border="1">
        <thead>
          <tr>
            <th>名前</th>
            <th>フリガナ</th>
            <th>e-mail</th>
            <th>メモ</th>
          </tr>
        </thead>
        <tbody>
          {% for Guest in Guests %}
            <tr>
              <td>{{ Guest.name }}</td>
              <td>{{ Guest.furi }}</td>
              <td>{{ Guest.email }}</td>
              <td>{{ Guest.memo }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </form>
  </body>
</html>

pollapp/templates/2/guestlistのコピー.html
<!DOCTYPE html>
<html>
<head>
  <title>参加者一覧</title>
</head>
  <body>

    <p>guestlist 参加者一覧</p>


    <table border="1">
      <thead>
        <tr>
          <th>名前</th>
          <th>フリガナ</th>
          <th>e-mail</th>
          <th>備考・同伴者</th>
        </tr>
      </thead>
      <tbody>
        {% for guest in guest_list %}
          <tr>
            <td>{{ guest.name }}</td>
            <td>{{ guest.furi }}</td>
            <td>{{ guest.email }}</td>
            <td>{{ guest.remarks }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </body>
</html>

pollapp/templates/2/mailsend.html
<!DOCTYPE html>
<html>
  <head>
  mailsend
  </head>
  <body>
    <p>このページはメール送信ページです</p>
    <p><a href="{% url 'pollapp:guestlist' %}">一覧へ</a></p>
  </body>
</html>

pollapp/templates/2/testpage.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>登録完了</title>
    <meta name= "viewport"
     content="width=device-width,user-scalable=no,maximum-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/testpage.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/testpage_res.css' %}">
  </head>
  <body>
    <header></header>
    <main>
      <p>以下のように登録が完了しました。</p>
      <table boder="0">
        {% for field in form %}
        <tr>
          <td>{{ field.label }}</td>
          <td>{{ field.value }}</td>
        </tr>
        {% endfor %}
      </table>
      <p>※イベント前日にリマインドメールが届きます。</p>
      <p>登録は以上です。画面を閉じてください。</p>
    </main>
  </body>
</html>